### ISSUE TITLE
Distribution type diagram - AI (and standard) are missing

### ISSUE THREAD

**Issue by PelinSmines** [DPGAlliance/publicgoods-scripts#214]
![Image](https://github.com/DPGAlliance/publicgoods-website/assets/8988279/afa3c0f1-96aa-4beb-8659-644b8029c34a)

[Data Explorer section in Registry page](https://digitalpublicgoods.net/registry/) has some consistency issues:
There is DPG types section for filtering:
AI Model, Open Content, Open Data, Open Software and Standard are the categories under this types section.
In the data visualisation section not all of these sub categories are reflected. There are only Content, Data and Software categories reflected.
The fix screen grab isn't about this error, this issue is regarding the tile map.

**Comment by gazdagergo** [comment]
D3 logic has been re-implemented. Some types (AI) and intersections has not been passed.

**UAT and AC:**
- visit https://digitalpublicgoods.net/registry/
- the colored venn diagramm under the "DISTRIBUTION BY TYPE" should show all dpg types correctly
- hovering the circles show a popup with the number of SDGs within the type
- clicking the circles triggers the filtering down on the list (the intersections does not)
