### ISSUE TITLE
Analytics should collect usage data to track base performance and visitor stats

### ISSUE THREAD

**Issue by PelinSmines** [DPGAlliance/publicgoods-scripts#218]
@SarahWat has the rights to add the GA tag. She will add the below tag into website or will give access to us to do it.

@skylark1848 @gazdagergo 

<script async src="https://www.googletagmanager.com/gtag/js?id=G-TB30F14ZPT"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-TB30F14ZPT');
</script>

**Comment by SarahWat** [comment]
Thank you to @ricardomiron who helped get this up yesterday! 
Can you check that it's pulling the right info now to GA, @gazdagergo & @PelinSmines?

**Comment by PelinSmines** [comment]
Data flow is broken again.

**Comment by skylark1848** [comment]
This was set up again with Monster Insights. Analytics seems to collect data only from the Heroku instance, so the fix is not straightforward with the current structure. We are looking into it.

**Comment by gazdagergo** [comment]
**AC**

- logging into GA you can see the live data

**Comment by skylark1848** [comment]
AC update, let's wait to see if it is working for some more time
