### ISSUE TITLE
BUG on Eligibility form

### ISSUE THREAD

**Issue by PelinSmines** [DPGAlliance/publicgoods-scripts#226]
There's an eligibility checking form. 10 Yes/No questions are being answered and at the end a short assessment message comes out based on the answer. If the overall assessment is positive about being eligible, there's a button to proceed. Clicking on "Proceed" must open another tab: it's written; _Please wait, a new tab will be opened to continue the application process._

This information is given by a pop up box. However, when clicking on Proceed button, a new tab doesn't open. Nothing happens. It should have https://app.digitalpublicgoods.net/signup as the destination. The error might be related to #216 
Also, do we need this info box? If the Proceed button works and it opens a new tab, we don't need to read a message in a pop up box about what to happen next. This problem is observed both on Safari and Chrome.

<img width="872" alt="Screenshot 2023-10-06 at 17 06 50" src="https://github.com/DPGAlliance/publicgoods-scripts/assets/123653036/14332e5e-cbc2-406a-8442-c2785016ea8e">

**Comment by law909** [comment]
After clicking the Proceed button, the code called a nonexistent API endpoint and tried to save the answers. This call blocked opening of the signup page.
I removed the call and removed the pop up form too.

**Comment by gazdagergo** [comment]
UAT / AC

- visit the https://digitalpublicgoods.net/eligibility/ url
- click to register, select "Yes" on every page and click "Next"
- on the last page, click "Proceed"
- the url https://app.digitalpublicgoods.net/signup should be open on a new tab
