### ISSUE TITLE
BUG on Registry Website when SDGs are deselected 

### ISSUE THREAD

**Issue by PelinSmines** [DPGAlliance/publicgoods-scripts#227]
When all the SDGs are deselected, the SDG list stays under the page footer.  see the attached screen recording.

https://github.com/DPGAlliance/publicgoods-scripts/assets/123653036/c1417950-dafe-44cd-a352-164acc988f2d

**Comment by gazdagergo** [comment]
**Acceptance Criteria** (steps for user acceptance test)
- visit the https://digitalpublicgoods.net/registry/ page
- deselect all types except Software and deselect all SDGs
- scroll the page to the bottom, and back upwards
- the footer should NOT cover the page main section during the scroll

**Comment by gazdagergo** [comment]
The root issue is the bad usability of the long DPGA list during filtering. They tried to solve it with a "sticky" behaviour of the checkbox list, but the implementation of this sticky thingy was incorrect and that caused the weird footer behaviour. This fix has been removed the bad sticky behaviour. We can talk about it later how to enhance the filter usability (by e.g. pagination).
