### ISSUE TITLE
[Registry Mobile] Registry Page_Mobile compatibility of the DPGA website

### ISSUE THREAD

**Issue by PelinSmines** [DPGAlliance/publicgoods-scripts#231]
Currently other than the WP based pages, DPGA website is not mobile responsive.
Especially the Roadmap and the Registry pages are not compatible.
There are also couple of UI bugs to be fixed.
**Registry page:**
In mobile version we will **NOT** have the:
- Data explorer section with Venn diagrams
- Distribution by SDG tiles
- "About the Digital Public Good Standard" Button / link See pic: ![IMG_2301](https://github.com/DPGAlliance/publicgoods-scripts/assets/123653036/fc2ef45e-175c-4834-a55b-469f41d21b77)

**UI fixes:**
- "Become a Digital Public Good" button and "DPG Eligibility Requirements" button should be aligned. See pic: ![IMG_2300](https://github.com/DPGAlliance/publicgoods-scripts/assets/123653036/3be2a7a8-23a5-4e9a-a397-144cbdd869c9)
- DPG types and SDG filters should be on top of the DPG list
- Filters shouldn't be listed as individual check boxes. Filters should be displayed as drop down menu under 2 filter options: DPG Type and SDGs
- Listed DPGs should be displayed only by Name and Description fields. 
- Nomination, DPGA Technical Team Review and Digital Public Good steps should be displayed side by side instead of one by one scrolled way. see pic: ![IMG_2299](https://github.com/DPGAlliance/publicgoods-scripts/assets/123653036/cc709f61-3f91-4d3d-b679-36f4c010a1b3)

**Comment by gazdagergo** [comment]
We split it onto multiple tickets, starting with a `[Registry Mobile]` in the title
