### ISSUE TITLE
[Registry Mobile] Remove sections from mobile version

### ISSUE THREAD

**Issue by law909** [DPGAlliance/publicgoods-scripts#234]
- Data explorer section with Venn diagrams
- Distribution by SDG tiles
- ~~"About the Digital Public Good Standard" Button~~

**Comment by law909** [comment]
The "About the Digital Public Good Standard" button is wordpress content, can be hidden from wp admin or through the wp theme.

**Comment by gazdagergo** [comment]
**Acceptance Criteria / User Acceptance Test**
- visit the https://digitalpublicgoods.net/registry/ url on a mobile device or emulated mobile width in browser
- the data section with number and Venn diagramm should NOT be visible
- the tiles diagram should NOT be visible
