### ISSUE TITLE
[Registry Mobile][WP theme] Fix button alignment

### ISSUE THREAD

**Issue by law909** [DPGAlliance/publicgoods-scripts#235]
"Become a Digital Public Good" button and "DPG Eligibility Requirements" button should be aligned

**Comment by law909** [comment]
Wordpress theme issue

**Comment by skylark1848** [comment]
Acceptance Criteria:

URL https://digitalpublicgoods.net/registry/

Set size to iPhone SE or other mobile screen

"Become a Digital Public Good"
"DPG Eligibility Requirements"

buttons should be centered on page.

![Image](https://github.com/DPGAlliance/publicgoods-scripts/assets/4942278/c49f1ce1-30ee-48b3-936f-e7faf2808f0a)
