### ISSUE TITLE
[Registry Mobile][WP theme] Remove sections from mobile version

### ISSUE THREAD

**Issue by law909** [DPGAlliance/publicgoods-scripts#239]
"About the Digital Public Good Standard" Button

**Comment by skylark1848** [comment]
Acceptance Criteria:

URL: https://digitalpublicgoods.net/registry/

"About the Digital Public Good Standard" is visible on desktop



![Image](https://github.com/DPGAlliance/publicgoods-scripts/assets/4942278/0aaeabf2-1fea-4339-acd6-882a109943ed)


Set screen size to mobile such as iPhone SE, and "About the Digital Public Good Standard" text and link should disappear.

![Image](https://github.com/DPGAlliance/publicgoods-scripts/assets/4942278/352d9d7f-8e61-41a3-ac9b-1f8a4c45bbad)
