### ISSUE TITLE
DPG Badges

### ISSUE THREAD

**Issue by PelinSmines** [DPGAlliance/publicgoods-scripts#246]
Currently each DPG has a DPG badge next to their title in the Registry. This is not needed as only the DPGs are listed anyway. We don't list the nominees or expired DPGs. So instead of the same DPG badge repeating for each DPG in the list, we need to put a "DPG type" badge for each DPG listed. This information is under "Solution Category" for each DPG. The categories are:

1. Open Software
2. Open Data
3. Open Standard (There's no standard DPGs atm.)
4. Open Content
5. Open AI Model

A DPG may have more than 1 category assigned to it. Then we can use more than 1 badge for it. 
In the category filter, next to the category title we can use the badge of that category which can function as a ledger for the badges as well. 
The badges are here: https://drive.google.com/drive/folders/1QitVA-oPSYMcPOYL8paC4s8tCT5zugno?usp=share_link

**Comment by gazdagergo** [comment]
Design proposal for the badges. Colors can vary based on company color guideline.



![Image](https://github.com/DPGAlliance/publicgoods-scripts/assets/8988279/441ae7b5-96ce-4d57-8903-414041f6349e)

**Comment by PelinSmines** [comment]
@gazdagergo This solution is approved by Jameson and Ricardo. So we are going with the proposed badges in different colours. Please use the colours in this brand guide.
![DPGA Brand Guide](https://github.com/DPGAlliance/publicgoods-scripts/assets/123653036/31b80a04-dfa7-40a0-93ba-5c77d9d7f820)
In the badges please use the singular form:
Software
AI Model
Standard
Content
Data
We won't need the DPG badge in here anymore.

**Comment by PelinSmines** [comment]
Related to the issue: https://github.com/DPGAlliance/publicgoods-scripts/issues/250

**Comment by gazdagergo** [comment]
The new look with the guideline colors:


![Image](https://github.com/DPGAlliance/publicgoods-scripts/assets/8988279/b8b9b130-31cf-4685-9797-65e70d5f5c32)
