### ISSUE TITLE
Github activity graph is not shown for DPGs

### ISSUE THREAD

**Issue by PelinSmines** [DPGAlliance/publicgoods-scripts#248]
On Registry page we show the Last year activity of the DPGs via Github.
Currently only these products seem to have last year activity:
[Bisa Health](https://app.digitalpublicgoods.net/a/10768)
[ekShop Marketplace](https://app.digitalpublicgoods.net/a/10555)
[NiSE3 Skills and Certification](https://app.digitalpublicgoods.net/a/10835)
[Safe YOU](https://app.digitalpublicgoods.net/a/10514)

For example this DPG (https://app.digitalpublicgoods.net/a/11138) has activity in Github:
https://github.com/investtools/ivttoken but it is not visible in Registry.

All the DPGS that have source code in Github and have activity in the past year must have their custom activity graph shown in the Registry list on the Registry page.

**Comment by law909** [comment]
Github changed their way to draw activity graph and changed their pages HTML structure. We try to extract the activity graph from pages like [this](https://github.com/orgs/coronasafe/repositories?q=care&sort=stargazers) from some "poll[src]" tags but there is no tags like that.
By the way, if an organization has multiple repositories, our current code downloaded the activity graph of the most starred repo, even if it wasn't the DPG's repository.

Needs a complete rewrite.

**Comment by PelinSmines** [comment]
@law909 @gazdagergo as it looks like, we may have this graph in the new version of the Registry. Both the product owners and the members seem to find it useful. So we need to assess the re-write of this feature.

**Comment by law909** [comment]
@PelinSmines There is no official way to get the graph. We can try to get it by scraping the user's main page html, but it is really a workaround that will stop working again when Github changes the HTML of that page.
It is more likely that we won't be able to do it than that we will.

**Comment by PelinSmines** [comment]
What about using [this](https://github.com/dhis2/dhis2-core/graphs/commit-activity) or [this](https://github.com/dhis2/dhis2-core/graphs/contributors) info @law909 ? I will ask Ricardo which is more preferable from usefulness pov.

**Comment by law909** [comment]
@PelinSmines there are some APIs to access those data, I will check what we can access through those.

**Comment by gazdagergo** [comment]
@PelinSmines We did a quick task refinement with Balint @law909 , and we agreed that it’s definitely possible to do this the proper way. However, it requires further analysis on authentication, data fetching, and visualization. Once we have that, we can provide an estimate and ideally this task can go to the roadmap to make its priority and deadline more visible.

As a fallback, we could fix the scraper logic that collects the images from GitHub. However, this method is unreliable, as it can cause silent errors if GitHub changes its HTML structure.

**Comment by law909** [comment]
https://docs.github.com/en/rest/metrics/statistics?apiVersion=2022-11-28#about-repository-statistics

**Comment by PelinSmines** [comment]
What about this: https://docs.github.com/en/rest/metrics/statistics?apiVersion=2022-11-28#get-the-last-year-of-commit-activity @law909 @gazdagergo

**Comment by PelinSmines** [comment]
#66

**Comment by PelinSmines** [comment]
@law909 https://github.com/DPGAlliance/publicgoods-review-webapp-v1.5/issues/66 related?
