### ISSUE TITLE
Deprecated page keeps getting build in the production website

### ISSUE THREAD

**Issue by ricardomiron** [DPGAlliance/publicgoods-scripts#253]
The script(s) that build the public website (hosted in GH Pages) from [this repo](https://github.com/DPGAlliance/publicgoods-website) keeps building (at least) this page - https://digitalpublicgoods.net/implement/  [[https://github.com/DPGAlliance/publicgoods-website/tree/main/implement](https://github.com/DPGAlliance/publicgoods-website/tree/main/implement)] which is no longer part of what we want in the website and it does not comes from WordPress (where we manage content).

**Comment by law909** [comment]
@ricardomiron I think we can delete these old "ghost" pages from the repo, please check:

https://digitalpublicgoods.net/submission-guide/
https://digitalpublicgoods.net/strategy
https://digitalpublicgoods.net/resources
https://digitalpublicgoods.net/registry/AI_Agro.html and all the generated pages of DPGs
https://digitalpublicgoods.net/newsletter do you use this mailchimp acc?
https://digitalpublicgoods.net/join
https://digitalpublicgoods.net/implement
https://digitalpublicgoods.net/helpcenter
https://digitalpublicgoods.net/digital-public-goods-alliance-strategy-2021-2026

**Comment by law909** [comment]
@ricardomiron there are some pdfs and pages that links to those pdfs, please check if you need any of them

**Comment by PelinSmines** [comment]
> [@ricardomiron](https://github.com/ricardomiron) I think we can delete these old "ghost" pages from the repo, please check:
> @law909 I had a first look and here are my comments: 
> https://digitalpublicgoods.net/submission-guide/ This page looks like it could be used. It has a working link that directs to the DPG nomination form.
https://digitalpublicgoods.net/strategy This strategy document is referred to in several places in the website. However, it should direct to the one here: https://digitalpublicgoods.net/DPGA_Strategy_2021-2026.pdf  
https://digitalpublicgoods.net/resources This is not opening. 
https://digitalpublicgoods.net/registry/AI_Agro.html and all the generated pages of DPGs 
https://digitalpublicgoods.net/newsletter do you use this mailchimp acc? 
https://digitalpublicgoods.net/join This page looks like a typical ghost page
https://digitalpublicgoods.net/implement Same as above
https://digitalpublicgoods.net/helpcenter This looks like Ricardo's guidebook. Not sure if he still uses this for the community guidance. 
https://digitalpublicgoods.net/digital-public-goods-alliance-strategy-2021-2026

**Comment by ricardomiron** [comment]
Hi, here are my comments for each of these:

1. https://digitalpublicgoods.net/submission-guide/ - this guide is still in use (keep ✅)
2. https://digitalpublicgoods.net/strategy - there's an[ updated strategy PDF](https://digitalpublicgoods.net/dpga-strategy2023-2028.pdf) (update 🔄️)
3. https://digitalpublicgoods.net/resources - we can point this to [GitHub resources](https://github.com/DPGAlliance/dpg-resources) (update 🔄️)
4. https://digitalpublicgoods.net/registry/AI_Agro.html and all the generated pages of DPGs - not in use anymore (remove ❌)
5. https://digitalpublicgoods.net/newsletter do you use this mailchimp acc? Yes this is still valid (keep ✅)
6. https://digitalpublicgoods.net/join (remove ❌)
7. https://digitalpublicgoods.net/implement (remove ❌)
8. https://digitalpublicgoods.net/helpcenter - point to the [DPG Wiki](https://github.com/DPGAlliance/dpg-resources/wiki) (update 🔄️)
9. https://digitalpublicgoods.net/digital-public-goods-alliance-strategy-2021-2026 (keep ✅)

@law909 we should keep all PDFs and their pages, these are linked in multiple places externally
