### ISSUE TITLE
Explore Frontend Logger libraries to playback errors on  Eligibility and Submission forms 

### ISSUE THREAD

**Issue by nathanfletcher** [DPGAlliance/publicgoods-scripts#41]
Libraries to look at integrating on  Eligibility and Submission forms :

- Vercel integrations - @lacabra 
- [Sentry](https://sentry.io/welcome/)
- [LogRocket](https://logrocket.com/)
- [DataDog](https://www.datadoghq.com/)

**Comment by nathanbaleeta** [comment]
Closing this issue as the logging enhancement may no logger be necessary in the current submissions form  - work is progress to migrate to the [new webApp](https://dpga.gtechjaipur.com/signup) before end of 2022. Thanks.

**Comment by nathanbaleeta** [comment]
> progress
